"""initial_migration

Revision ID: 6b9fc80af9e1
Revises: 
Create Date: 2025-10-16 15:54:53.583190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b9fc80af9e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mto_embedding_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mto_text', sa.Text(), nullable=False),
    sa.Column('mto_text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mto_text')
    )
    op.create_index(op.f('ix_mto_embedding_cache_mto_text_hash'), 'mto_embedding_cache', ['mto_text_hash'], unique=True)
    op.alter_column('activity_logs', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('activity_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('activity_logs', 'user',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('activity_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('activity_logs', 'details',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('inventory_items', sa.Column('embedding_vector', sa.JSON(), nullable=True))
    op.add_column('inventory_items', sa.Column('embedding_text', sa.Text(), nullable=True))
    op.add_column('inventory_items', sa.Column('embedding_updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_inventory_warehouse_item_num', table_name='inventory_items')
    op.alter_column('iso_file_index', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('iso_file_index', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('iso_file_index', 'normalized_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('iso_file_index', 'prefix_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('iso_file_index', 'last_modified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_16630_ix_iso_file_index_normalized_name', table_name='iso_file_index')
    op.drop_index('idx_16630_ix_iso_file_index_prefix_key', table_name='iso_file_index')
    op.drop_index('idx_16630_sqlite_autoindex_iso_file_index_1', table_name='iso_file_index')
    op.create_index(op.f('ix_iso_file_index_normalized_name'), 'iso_file_index', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_iso_file_index_prefix_key'), 'iso_file_index', ['prefix_key'], unique=False)
    op.create_unique_constraint(None, 'iso_file_index', ['file_path'])
    op.alter_column('migrated_files', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('migrated_files', 'filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('migrated_files', 'migrated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_16589_sqlite_autoindex_migrated_files_1', table_name='migrated_files')
    op.create_unique_constraint(None, 'migrated_files', ['filename'])
    op.alter_column('miv_records', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('miv_records', 'project_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('miv_records', 'line_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('miv_records', 'miv_tag',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('miv_records', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('miv_records', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('miv_records', 'comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('miv_records', 'registered_for',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('miv_records', 'registered_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('miv_records', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_16594_sqlite_autoindex_miv_records_1', table_name='miv_records')
    op.create_index('ix_miv_records_project_line', 'miv_records', ['project_id', 'line_no'], unique=False)
    op.create_unique_constraint(None, 'miv_records', ['miv_tag'])
    op.create_foreign_key(None, 'mto_consumption', 'inventory_items', ['inventory_item_id'], ['id'])
    op.alter_column('mto_items', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('mto_items', 'project_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('mto_items', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mto_items', 'line_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('mto_items', 'item_class',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mto_items', 'item_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mto_items', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mto_items', 'item_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mto_items', 'material_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_mto_items_project_line', 'mto_items', ['project_id', 'line_no'], unique=False)
    op.alter_column('mto_progress', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('mto_progress', 'project_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('mto_progress', 'line_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('mto_progress', 'mto_item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('mto_progress', 'item_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mto_progress', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mto_progress', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mto_progress', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_16604_sqlite_autoindex_mto_progress_1', table_name='mto_progress')
    op.create_unique_constraint('uq_progress_item', 'mto_progress', ['project_id', 'line_no', 'item_code', 'mto_item_id'])
    op.alter_column('projects', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('projects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_index('idx_16579_sqlite_autoindex_projects_1', table_name='projects')
    op.create_unique_constraint(None, 'projects', ['name'])
    op.alter_column('spool_consumption', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('spool_consumption', 'spool_item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('spool_consumption', 'spool_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('spool_consumption', 'miv_record_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('spool_consumption', 'used_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('spool_consumption', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('spool_items', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('spool_items', 'spool_id_fk',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('spool_items', 'component_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('spool_items', 'material',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('spool_items', 'schedule',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('spool_items', 'item_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('spool_progress', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('spool_progress', 'spool_item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spool_progress', 'spool_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spool_progress', 'project_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spool_progress', 'line_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('spool_progress', 'item_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('spool_progress', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('spools', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('spools', 'spool_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('spools', 'row_no',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spools', 'line_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('spools', 'sheet_no',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spools', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('spools', 'command',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_16612_sqlite_autoindex_spools_1', table_name='spools')
    op.create_unique_constraint(None, 'spools', ['spool_id'])
    op.add_column('warehouse_stock_snapshots', sa.Column('high_turnover_items', sa.JSON(), nullable=True))
    op.add_column('warehouse_stock_snapshots', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_snapshot_date', table_name='warehouse_stock_snapshots')
    op.drop_index('idx_snapshot_warehouse', table_name='warehouse_stock_snapshots')
    op.drop_constraint('uq_warehouse_snapshot', 'warehouse_stock_snapshots', type_='unique')
    op.create_index('idx_snapshot_warehouse_date', 'warehouse_stock_snapshots', ['warehouse_id', 'snapshot_date'], unique=False)
    op.create_unique_constraint('uq_warehouse_snapshot_date', 'warehouse_stock_snapshots', ['warehouse_id', 'snapshot_date'])
    op.drop_constraint('warehouses_code_key', 'warehouses', type_='unique')
    op.drop_index('ix_warehouses_code', table_name='warehouses')
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.create_index('ix_warehouses_code', 'warehouses', ['code'], unique=False)
    op.create_unique_constraint('warehouses_code_key', 'warehouses', ['code'])
    op.drop_constraint('uq_warehouse_snapshot_date', 'warehouse_stock_snapshots', type_='unique')
    op.drop_index('idx_snapshot_warehouse_date', table_name='warehouse_stock_snapshots')
    op.create_unique_constraint('uq_warehouse_snapshot', 'warehouse_stock_snapshots', ['warehouse_id', 'snapshot_date'])
    op.create_index('idx_snapshot_warehouse', 'warehouse_stock_snapshots', ['warehouse_id'], unique=False)
    op.create_index('idx_snapshot_date', 'warehouse_stock_snapshots', ['snapshot_date'], unique=False)
    op.drop_column('warehouse_stock_snapshots', 'created_at')
    op.drop_column('warehouse_stock_snapshots', 'high_turnover_items')
    op.drop_constraint(None, 'spools', type_='unique')
    op.create_index('idx_16612_sqlite_autoindex_spools_1', 'spools', ['spool_id'], unique=False)
    op.alter_column('spools', 'command',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spools', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spools', 'sheet_no',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spools', 'line_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spools', 'row_no',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spools', 'spool_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('spools', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('spool_progress', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('spool_progress', 'item_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spool_progress', 'line_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spool_progress', 'project_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spool_progress', 'spool_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spool_progress', 'spool_item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spool_progress', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('spool_items', 'item_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spool_items', 'schedule',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spool_items', 'material',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spool_items', 'component_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spool_items', 'spool_id_fk',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('spool_items', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('spool_consumption', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('spool_consumption', 'used_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('spool_consumption', 'miv_record_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('spool_consumption', 'spool_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('spool_consumption', 'spool_item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('spool_consumption', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_index('idx_16579_sqlite_autoindex_projects_1', 'projects', ['name'], unique=False)
    op.alter_column('projects', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('uq_progress_item', 'mto_progress', type_='unique')
    op.create_index('idx_16604_sqlite_autoindex_mto_progress_1', 'mto_progress', ['project_id', 'line_no', 'item_code', 'mto_item_id'], unique=False)
    op.alter_column('mto_progress', 'last_updated',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('mto_progress', 'unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mto_progress', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mto_progress', 'item_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mto_progress', 'mto_item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('mto_progress', 'line_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('mto_progress', 'project_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('mto_progress', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_mto_items_project_line', table_name='mto_items')
    op.alter_column('mto_items', 'material_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mto_items', 'item_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mto_items', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mto_items', 'item_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mto_items', 'item_class',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mto_items', 'line_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('mto_items', 'unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mto_items', 'project_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('mto_items', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'mto_consumption', type_='foreignkey')
    op.drop_constraint(None, 'miv_records', type_='unique')
    op.drop_index('ix_miv_records_project_line', table_name='miv_records')
    op.create_index('idx_16594_sqlite_autoindex_miv_records_1', 'miv_records', ['miv_tag'], unique=False)
    op.alter_column('miv_records', 'last_updated',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('miv_records', 'registered_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('miv_records', 'registered_for',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('miv_records', 'comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('miv_records', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('miv_records', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('miv_records', 'miv_tag',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('miv_records', 'line_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('miv_records', 'project_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('miv_records', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'migrated_files', type_='unique')
    op.create_index('idx_16589_sqlite_autoindex_migrated_files_1', 'migrated_files', ['filename'], unique=False)
    op.alter_column('migrated_files', 'migrated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('migrated_files', 'filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('migrated_files', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'iso_file_index', type_='unique')
    op.drop_index(op.f('ix_iso_file_index_prefix_key'), table_name='iso_file_index')
    op.drop_index(op.f('ix_iso_file_index_normalized_name'), table_name='iso_file_index')
    op.create_index('idx_16630_sqlite_autoindex_iso_file_index_1', 'iso_file_index', ['file_path'], unique=False)
    op.create_index('idx_16630_ix_iso_file_index_prefix_key', 'iso_file_index', ['prefix_key'], unique=False)
    op.create_index('idx_16630_ix_iso_file_index_normalized_name', 'iso_file_index', ['normalized_name'], unique=False)
    op.alter_column('iso_file_index', 'last_modified',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('iso_file_index', 'prefix_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('iso_file_index', 'normalized_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('iso_file_index', 'file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('iso_file_index', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index('ix_inventory_warehouse_item_num', 'inventory_items', ['warehouse_item_number'], unique=False)
    op.drop_column('inventory_items', 'embedding_updated_at')
    op.drop_column('inventory_items', 'embedding_text')
    op.drop_column('inventory_items', 'embedding_vector')
    op.alter_column('activity_logs', 'details',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('activity_logs', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('activity_logs', 'user',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('activity_logs', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('activity_logs', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_mto_embedding_cache_mto_text_hash'), table_name='mto_embedding_cache')
    op.drop_table('mto_embedding_cache')
    # ### end Alembic commands ###
